### ISSUE TITLE
Output is even larger

### ISSUE THREAD

**Issue by ImJoeHs** [idiotWu/canvas-compress#2]
![y bke pd 2cqz_qzbf k](https://user-images.githubusercontent.com/13445155/27534304-2708f634-5a99-11e7-929e-59891e8bdc05.png)

Happened in latest version of chrome/edge, either png or jpg.

**Comment by dolphin-wood** [comment]
Yeah sometimes it happens, especially when processing optimized images.

I'm afraid I may have nothing to do with this issue, since this project doesn't do any bitmap manipulations :(
